
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate



automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml



modbus: !include modbus.yaml

# sensor: !include sensors.yaml
# sensor: !include eskom.yaml
# sensor: !include EskomSePush.yaml

# hikvision: !include hikvision.yaml
sensor:
- platform: rest
  name: esp_loadshedding
  resource: https://developer.sepush.co.za/business/2.0/area?id=eskde-10-fourwaysext10cityofjohannesburggauteng
  headers:
    token: EskomSePushToken
  json_attributes:
    - events
  scan_interval: 3600
  value_template: '{{ value_json.info.name }}'

template:
  #Split power in and out of battery
  - sensor:
      - name: "Battery Power Charging"
        unit_of_measurement: "W"
        unique_id: battery_charging_power
        device_class: power
        state: >
          {% if states('sensor.battery_power')|float >= 0 %}
            {{ states('sensor.battery_power') }}
          {% else %}
            0
          {% endif %}
      - name: "Battery Power Discharging"
        unit_of_measurement: "W"
        unique_id: battery_discharging_power
        device_class: power
        state: >
          {% if states('sensor.battery_power')|float < 0 %}
            {{ -1 * states('sensor.battery_power')|float }}
          {% else %}
            0
          {% endif %}

# Integrate each power sensor into energy separately
sensor:
  - platform: integration
    source: sensor.battery_charging_power
    unique_id: battery_charged_energy2
    name: 'Battery Energy Charged'
    unit_prefix: k
    # unit_of_measurement: kW
    # device_class: energy
    round: 2

sensor:
  - platform: integration
    source: sensor.battery_discharging_power
    unique_id: battery_discharged_energy2
    name: 'Battery Energy Discharged'
    unit_prefix: k
    # unit_of_measurement: kW
    # device_class: energy
    round: 2      

sensor:
  - platform: rest
    name: esp_loadshedding
    resource: https://developer.sepush.co.za/business/2.0/area?id=eskde-10-fourwaysext10cityofjohannesburggauteng
    headers:
      token: EskomSePushToken
    json_attributes:
      - events
    scan_interval: 3600
    value_template: '{{ value_json.info.name }}'

sensor:
  - platform: template
    sensors:
      your_tarif:
        friendly_name: Eskom Tarrif
        unit_of_measurement: R/kWh
        value_template: >
          {% set tariff = { "HT": 2.65, "LT": 2.65 } %}
          {% if (now().weekday() < 5 and (7 <= now().hour <= 20)) or (now().weekday() == 5 and (7 <= now().hour <= 13)) %}
            {{ tariff.HT }}
          {% else %}
            {{ tariff.LT }}
          {% endif %}

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 300
    consider_home: 360

binary_sensor:
  - platform: hikvision
    host: 192.168.1.150
    username: admin
    password: Slowpolo1

