
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# sensor: !include sensors.yaml
modbus: !include modbus.yaml
# sensor: !include eskom.yaml
sensor: !include EskomSePush.yaml

# hikvision: !include hikvision.yaml

sensor:
  - platform: template
    sensors:
      your_tarif:
        friendly_name: Eskom Tarrif
        unit_of_measurement: R/kWh
        value_template: >
          {% set tariff = { "HT": 2.65, "LT": 2.65 } %}
          {% if (now().weekday() < 5 and (7 <= now().hour <= 20)) or (now().weekday() == 5 and (7 <= now().hour <= 13)) %}
            {{ tariff.HT }}
          {% else %}
            {{ tariff.LT }}
          {% endif %}
    