          
# Example Pi info configuration.yaml entry with all entry types (delete/comment out as necessary)
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      
      
#   - platform: mqtt
#     name: "Arduino MQTT Time On"
#     state_topic: "/homeassistant/test_arduino/time_onn"


# sensor:
#   - platform: rest
#     name: esp_loadshedding
#     resource: https://developer.sepush.co.za/business/2.0/area?id=eskde-10-fourwaysext10cityofjohannesburggauteng
#     headers:
#       token: !secret EskomSePushToken
#       json_attributes:
#         - events
#       scan_interval: 3600
#       value_template: '{{ value_json.info.name }}'

  - platform: template
    sensors:
      ac_power_total:
        friendly_name: "AC Consumption"
        value_template: "{{ states('sensor.ac_consumption_l1') | float + states('sensor.ac_consumption_l2') | float +  states('sensor.ac_consumption_l3') | float }}"
        unit_of_measurement: 'watts'
        unique_id: ac_consumption_total
        
  - platform: template
    sensors:
      grid_power_total:
        friendly_name: "Grid Power"
        value_template: "{{ states('sensor.grid_l1') | float + states('sensor.grid_l2') | float +  states('sensor.grid_l3') | float }}"
        unit_of_measurement: 'watts'
        unique_id: grid_power_total
