sensor:

# Sensors for energy dashboard
       
  # - platform: integration
  #   source: sensor.battery_charge_power
  #   name: Battery Charge
  #   unit_prefix: k
  #   round: 2

  # - platform: integration
  #   source: sensor.battery_discharge_power
  #   name: Battery Discharge
  #   unit_prefix: k
  #   round: 2