sensor:
    - name: 'Next Loadshedding'
      device_class: timestamp
      state: >
        {{ strptime(states.sensor.esp_loadshedding.attributes.events[0].start, '%Y-%m-%dT%H:%M:%S%z') }}
    - name: 'Minutes to next loadshedding'
      state: >
        {{ ((strptime(states.sensor.esp_loadshedding.attributes.events[0].start, '%Y-%m-%dT%H:%M:%S%z') - now() ).seconds/60) | int }}